### ISSUE TITLE
Issue with payload type when creating a new point

### ISSUE THREAD

**Issue by mirasakibara** [qdrant/qdrant_client#14] opened 2021-12-29 05:27 UTC
Hello everyone! I have a problem creating a new point. When I set the payload for a new vector, they all turn into a **string**. Because of this, I cannot further filter vectors with **Range()**.

`client.http.points_api.update_points(
    name=COLLECTION_NAME,
    wait=True,
    collection_update_operations=PointOperationsAnyOf(
        upsert_points=PointInsertOperationsAnyOf1(
            points=[
                PointStruct(
                    id=123,
                    payload={'value': random.random()},
                    vector=np.random.rand(DIM).tolist()
                )
            ]
        )
    )
)`

Output:
`(ScoredPoint(id=123, payload=None, score=24.59514, version=0), {'value': ['0.0510552054339094']})`

`'value': ['0.0510552054339094']`
I tried to do update the payload but in the end, it was string type.

**Comment by generall** [comment] 2021-12-29 11:36
Looks like the problem is related to https://pydantic-docs.helpmanual.io/usage/model_config/#smart-union

**Comment by mirasakibara** [comment] 2021-12-29 12:10
Thank you for your help!!!

**Comment by generall** [comment] 2021-12-29 12:14
Also related to https://github.com/samuelcolvin/pydantic/issues/1098

(Reopen issue, cause it should be fixed)

**Closed** 2022-06-08 15:20 UTC
Labels: bug
